all:
	g++ --std=c++11 -O2 -lpthread -o client_UDP.out client_UDP.cpp
	g++ --std=c++11 -O2 -lpthread -o client_TCP.out client_TCP.cpp
	g++ --std=c++11 -O2 -lpthread -o server_P1.out server_P1.cpp
	g++ --std=c++11 -O2 -lpthread -o server_P2.out server_P2.cpp
	g++ --std=c++11 -O2 -lpthread -o server_P3.out server_P3.cpp

