#!/bin/sh -e
if [ $1 = "on" ] ;then
  echo "Starting Packet Loss."
  sudo tc qdisc add dev lo root netem loss 5% delay 20ms 5ms distribution normal
elif [ $1 = "off" ] ;then
  echo "Stopping Packet Loss"
  sudo tc qdisc del dev lo root
fi
