
server:
	g++ --std=c++11 server.cpp -o server.out
run_server: server
	./server.out 5000
client:
	g++ --std=c++11 client.cpp -o client.out
file_test:
	g++ --std=c++11 file_test.cpp -o file.out
	./file.out
